// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(SystemContext))]
    [Migration("20210922094641_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Entities.Account", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailOptIn")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Email");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Email = "CMC1@gmail.com",
                            DOB = new DateTime(2021, 9, 22, 16, 46, 41, 372, DateTimeKind.Local).AddTicks(9663),
                            Gender = 0,
                            MobileNumber = "0909090909",
                            Name = "NgokHoi",
                            Password = "f8cgamafgO7tEl6Y67qRrOK4JytFm3XIYxaHHhPwc74=|WkOOdSuKNVpzFOG9A3eGnA=="
                        },
                        new
                        {
                            Email = "CMC2@gmail.com",
                            DOB = new DateTime(2021, 9, 22, 16, 46, 41, 373, DateTimeKind.Local).AddTicks(8862),
                            Gender = 0,
                            MobileNumber = "0909090999",
                            Name = "NgokHoi1234",
                            Password = "f8cgamafgO7tEl6Y67qRrOK4JytFm3XIYxaHHhPwc74=|WkOOdSuKNVpzFOG9A3eGnA=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
